version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    open-pull-requests-limit: 5
    groups:
      go-deps:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /examples
    schedule:
      interval: weekly
    labels:
      - dependencies
    open-pull-requests-limit: 3

  - package-ecosystem: gomod
    directory: /lru/benchmark
    schedule:
      interval: weekly
    labels:
      - dependencies
    open-pull-requests-limit: 3

  - package-ecosystem: gomod
    directory: /zapctx/zapctxgin
    schedule:
      interval: weekly
    labels:
      - dependencies
    open-pull-requests-limit: 3

  - package-ecosystem: gomod
    directory: /zapctx/zapctxgrpc
    schedule:
      interval: weekly
    labels:
      - dependencies
    open-pull-requests-limit: 3

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
      - ci
    open-pull-requests-limit: 3
