#!/usr/bin/env bash
set -euo pipefail

go mod tidy -diff
go vet ./...
go test -race -coverprofile=coverage.out -covermode=atomic ./...
golangci-lint run ./...
staticcheck ./...
govulncheck ./...
gosec -exclude=G115,G301,G302,G304 -exclude-dir=examples ./...
